ardupilot_default_airframe: gazebo-iris
ardupilot_dir: ~/ardupilot
global_coordinates:
  altitude: 90.0
  latitude: 24.795750
  longitude: 120.991944
px4_default_airframe: gazebo-classic_iris
px4_dir: /home/ubuntu/PX4-Autopilot
